### ISSUE TITLE
Alert showing in portrait mode when using landscape mode

### ISSUE THREAD

**Issue by shubhank008** [dinhquan/DQAlertView#3]
Hey, nice library you got here~
But I am facing a small problem, while using ipad2 in landscape mode, the alert is showing in portrait mode

When I rotate ipad to portrait mode, alert stays same in portrait mode.

Any clue why this might be happening ?

**Comment by carayolthomas** [comment]
Hey! It looks like I got the same problem but showInView method doesn't fix it.

It's working great on iPhone portrait mode but the problem is on iPad landscape mode.

I am in a view controller and I call [myAlertView showInView:self.view].

Anyone know something about it?
